server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/v1/cars/**
        - id: motorbike-service
          uri: lb://motorbike-service
          predicates:
            - Path=/api/v1/motorbikes/**

# Para debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG